from abc import ABC, abstractmethod

from shadowauth.models.normalized_event import NormalizedEvent


class BaseParser(ABC):
    """
    Base class for every event parser supported by ShadowAuth.

    A parser is responsible for transforming a native security event
    into the common NormalizedEvent model.
    """

    @abstractmethod
    def parse(self, event: dict) -> NormalizedEvent:
        """
        Convert a native event into a NormalizedEvent.

        Parameters
        ----------
        event : dict
            Original event generated by a security data source.

        Returns
        -------
        NormalizedEvent
            Event converted to the ShadowAuth common schema.
        """
        pass