import { useEffect, useState } from "react";
import {
  Link2,
  RefreshCw,
  ShieldAlert,
} from "lucide-react";

import LoadingScreen from "../components/LoadingScreen";

import {
  getCorrelations,
  withMinimumDelay,
} from "../services/api";

import type {
  CorrelationResult,
} from "../types/api";


const MINIMUM_LOADING_TIME = 3000;


export default function CorrelationsPage() {
  const [correlations, setCorrelations] =
    useState<CorrelationResult[]>([]);

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState<string | null>(null);


  async function loadCorrelations() {
    setLoading(true);
    setError(null);

    try {
      const data = await withMinimumDelay(
        getCorrelations(100),
        MINIMUM_LOADING_TIME,
      );

      setCorrelations(data);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Could not load correlations."
      );
    } finally {
      setLoading(false);
    }
  }


  useEffect(() => {
    let cancelled = false;

    withMinimumDelay(
      getCorrelations(100),
      MINIMUM_LOADING_TIME,
    )
      .then((data) => {
        if (!cancelled) {
          setCorrelations(data);
          setError(null);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setError(
            err instanceof Error
              ? err.message
              : "Could not load correlations."
          );
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);


  if (loading) {
    return (
      <LoadingScreen
        title="Loading correlations"
        message="Analyzing persisted correlation matches and threat evidence."
      />
    );
  }


  return (
    <div className="data-page">
      <header className="page-header">
        <div>
          <p className="eyebrow">
            CORRELATION ENGINE
          </p>

          <h2>Correlations</h2>

          <p className="page-subtitle">
            Security detections generated by
            ShadowAuth correlation rules.
          </p>
        </div>

        <button
          className="refresh-button"
          onClick={loadCorrelations}
        >
          <RefreshCw size={16} />
          Refresh
        </button>
      </header>


      <section className="correlation-summary-grid">
        <article className="stat-card">
          <div className="stat-card-top">
            <span>Total matches</span>

            <div className="stat-icon">
              <Link2 size={20} />
            </div>
          </div>

          <strong className="stat-value">
            {correlations.length}
          </strong>

          <span className="stat-subtitle">
            Persisted correlation results
          </span>
        </article>


        <article className="stat-card">
          <div className="stat-card-top">
            <span>Ransomware</span>

            <div className="stat-icon">
              <ShieldAlert size={20} />
            </div>
          </div>

          <strong className="stat-value">
            {
              correlations.filter(
                (item) =>
                  item.threat_type ===
                  "ransomware"
              ).length
            }
          </strong>

          <span className="stat-subtitle">
            CORR-003 matches
          </span>
        </article>


        <article className="stat-card">
          <div className="stat-card-top">
            <span>Cryptojacking</span>

            <div className="stat-icon">
              <ShieldAlert size={20} />
            </div>
          </div>

          <strong className="stat-value">
            {
              correlations.filter(
                (item) =>
                  item.threat_type ===
                  "cryptojacking"
              ).length
            }
          </strong>

          <span className="stat-subtitle">
            CORR-004 matches
          </span>
        </article>


        <article className="stat-card">
          <div className="stat-card-top">
            <span>Suspicious</span>

            <div className="stat-icon">
              <ShieldAlert size={20} />
            </div>
          </div>

          <strong className="stat-value">
            {
              correlations.filter(
                (item) =>
                  item.threat_type ===
                  "suspicious_activity"
              ).length
            }
          </strong>

          <span className="stat-subtitle">
            CORR-001 matches
          </span>
        </article>
      </section>


      <section className="table-panel">
        {error && (
          <div className="table-state error">
            {error}
          </div>
        )}


        {!error && (
          <div className="correlation-list">
            {correlations.map((item) => (
              <article
                key={item.correlation_id}
                className="correlation-card"
              >
                <div className="correlation-card-top">
                  <div>
                    <div className="correlation-rule">
                      <span className="rule-id">
                        {item.rule_id}
                      </span>

                      <h3>
                        {item.rule_name}
                      </h3>
                    </div>

                    <p>
                      {item.description}
                    </p>
                  </div>


                  <span
                    className={
                      `severity-badge ${item.severity}`
                    }
                  >
                    {item.severity}
                  </span>
                </div>


                <div className="correlation-meta">
                  <div>
                    <span>Threat</span>

                    <strong>
                      {item.threat_type}
                    </strong>
                  </div>


                  <div>
                    <span>Session</span>

                    <strong className="mono-cell">
                      {item.session_id}
                    </strong>
                  </div>


                  <div>
                    <span>Score</span>

                    <strong>
                      {(item.score * 100).toFixed(0)}
                      %
                    </strong>
                  </div>


                  <div>
                    <span>Model</span>

                    <strong>
                      {item.model_name}
                      {" "}
                      v{item.model_version}
                    </strong>
                  </div>
                </div>


                <details className="evidence-box">
                  <summary>
                    View evidence
                  </summary>

                  <pre>
                    {JSON.stringify(
                      item.evidence,
                      null,
                      2
                    )}
                  </pre>
                </details>
              </article>
            ))}


            {correlations.length === 0 && (
              <div className="table-state">
                No correlation matches found.
              </div>
            )}
          </div>
        )}
      </section>
    </div>
  );
}