import { useEffect, useMemo, useState } from "react";
import {
  Brain,
  RefreshCw,
  ShieldAlert,
  ShieldCheck,
} from "lucide-react";

import LoadingScreen from "../components/LoadingScreen";

import {
  getMLScores,
  withMinimumDelay,
} from "../services/api";

import type {
  MLScore,
} from "../types/api";


const MINIMUM_LOADING_TIME = 3000;


export default function MachineLearningPage() {
  const [scores, setScores] =
    useState<MLScore[]>([]);

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState<string | null>(null);


  async function loadScores() {
    setLoading(true);
    setError(null);

    try {
      const data = await withMinimumDelay(
        getMLScores(500),
        MINIMUM_LOADING_TIME,
      );

      const filteredScores = data.filter(
        (score) =>
          score.model_name === "random_forest" &&
          score.model_version === "2.0"
      );

      setScores(filteredScores);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Could not load ML scores."
      );
    } finally {
      setLoading(false);
    }
  }


  useEffect(() => {
    let cancelled = false;

    withMinimumDelay(
      getMLScores(500),
      MINIMUM_LOADING_TIME,
    )
      .then((data) => {
        if (!cancelled) {
          const filteredScores = data.filter(
            (score) =>
              score.model_name === "random_forest" &&
              score.model_version === "2.0"
          );

          setScores(filteredScores);
          setError(null);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setError(
            err instanceof Error
              ? err.message
              : "Could not load ML scores."
          );
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);


  const summary = useMemo(() => {
    const attack = scores.filter(
      (score) =>
        score.prediction === "attack"
    ).length;

    const benign = scores.filter(
      (score) =>
        score.prediction === "benign"
    ).length;

    const probabilities = scores
      .map(
        (score) =>
          score.attack_probability
      )
      .filter(
        (value): value is number =>
          value !== null
      );

    const averageProbability =
      probabilities.length > 0
        ? probabilities.reduce(
            (total, value) =>
              total + value,
            0
          ) / probabilities.length
        : 0;

    return {
      attack,
      benign,
      averageProbability,
    };
  }, [scores]);


  if (loading) {
    return (
      <LoadingScreen
        title="Loading detection model"
        message="Retrieving Random Forest v2.0 inference results and prediction metrics."
      />
    );
  }


  if (error) {
    return (
      <div className="table-state error">
        {error}
      </div>
    );
  }


  return (
    <div className="data-page">
      <header className="page-header">
        <div>
          <p className="eyebrow">
            MACHINE LEARNING
          </p>

          <h2>Detection Model</h2>

          <p className="page-subtitle">
            Session predictions generated by
            Random Forest v2.0.
          </p>
        </div>


        <button
          className="refresh-button"
          onClick={loadScores}
        >
          <RefreshCw size={16} />
          Refresh
        </button>
      </header>


      <section className="ml-summary-grid">
        <MLCard
          label="Current model"
          value="Random Forest"
          detail="Version 2.0"
          icon={<Brain size={20} />}
        />


        <MLCard
          label="Persisted scores"
          value={scores.length}
          detail="v2.0 inference results"
          icon={<Brain size={20} />}
        />


        <MLCard
          label="Attack predictions"
          value={summary.attack}
          detail="Sessions predicted attack"
          icon={<ShieldAlert size={20} />}
        />


        <MLCard
          label="Benign predictions"
          value={summary.benign}
          detail="Sessions predicted benign"
          icon={<ShieldCheck size={20} />}
        />
      </section>


      <section className="panel ml-info-panel">
        <div>
          <span className="ml-info-label">
            Average attack probability
          </span>

          <strong className="ml-probability">
            {(
              summary.averageProbability *
              100
            ).toFixed(1)}
            %
          </strong>
        </div>


        <div>
          <span className="ml-info-label">
            Production candidate
          </span>

          <strong>
            random_forest v2.0
          </strong>
        </div>
      </section>


      <section className="table-panel">
        <div className="table-wrapper">
          <table className="security-table">
            <thead>
              <tr>
                <th>Session</th>
                <th>Prediction</th>
                <th>Attack probability</th>
                <th>Model</th>
                <th>Version</th>
                <th>Ground truth</th>
              </tr>
            </thead>


            <tbody>
              {scores.map((score) => {
                const groundTruth =
                  typeof score.metadata
                    .ground_truth ===
                  "string"
                    ? score.metadata
                        .ground_truth
                    : "—";

                return (
                  <tr key={score.score_id}>
                    <td className="mono-cell">
                      {score.session_id}
                    </td>


                    <td>
                      <span
                        className={
                          `label-badge ${score.prediction}`
                        }
                      >
                        {score.prediction}
                      </span>
                    </td>


                    <td>
                      {score.attack_probability !==
                      null
                        ? `${(
                            score.attack_probability *
                            100
                          ).toFixed(1)}%`
                        : "—"}
                    </td>


                    <td>
                      {score.model_name}
                    </td>


                    <td>
                      {score.model_version}
                    </td>


                    <td>
                      {groundTruth}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>


          {scores.length === 0 && (
            <div className="table-state">
              No Random Forest v2.0
              inference scores found.
            </div>
          )}
        </div>
      </section>
    </div>
  );
}


function MLCard({
  label,
  value,
  detail,
  icon,
}: {
  label: string;
  value: string | number;
  detail: string;
  icon: React.ReactNode;
}) {
  return (
    <article className="stat-card">
      <div className="stat-card-top">
        <span>
          {label}
        </span>

        <div className="stat-icon">
          {icon}
        </div>
      </div>


      <strong className="ml-card-value">
        {value}
      </strong>


      <span className="stat-subtitle">
        {detail}
      </span>
    </article>
  );
}